yandex:
  folder-id: b1gnf50itdkevdiab3it
  api:
    translate: https://translate.api.cloud.yandex.net/translate/v2/translate
    detect: https://translate.api.cloud.yandex.net/translate/v2/detect
    tokens: https://iam.api.cloud.yandex.net/iam/v1/tokens

giphy: https://api.giphy.com/v1

redis:
  host: localhost
  port: 6379
  password: 1q2w3e4r
